apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Wanderlust_project
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aakashrsethi39/Wanderlust_CICD_Project.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
